version: "3.9"
services:
  bookapi:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PAYARA_JDBC_URL=jdbc:postgresql://db:5432/books
      - PAYARA_JDBC_USER=bookuser
      - PAYARA_JDBC_PASSWORD=secret

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
